### ISSUE TITLE
Video not sent from Unity

### ISSUE THREAD

**Issue by NinoStella** [ritchielozada/UnityWithWebRTC#2]
I'm testing the code, in two differente scenario:
1) Machine A and Machine B running XamlTestApp application with two MediaElement for preview: all works as expexted and i can see both video streaming

2) Machine A running Unity project (build for UWP) and Machine B running XamlTestApp: the video stream from the Unity client is not sent (i can see the webcam turned on).

The wrapper is the same, so i suppose it is something related to unity. 

I'm using VP8 codec.

**Comment by ritchielozada** [comment]
The Unity client does not send video/audio as a peer, it is meant to only receive.  (I'm updating the README to include these issues)

The webcam/mic is activated due to an issue we have identified with the WebRTC UWP Lib Wrapper which requires a video/audio device to be defined otherwise it will crash.  On the native webrtc lib, we are able to create a dummy device to avoid this issue.   We are trying to resolve this on a parallel project.

**Comment by w493901539** [comment]
Can't release this in unity 

UnityException: Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\WebRtcWrapper.dll" "-pdb" "-verbose" "-unity-engine=Temp\StagingArea\Data\Managed\UnityEngine.dll" "Temp\StagingArea\TempSerializationWeaver" "-lock=UWP\project.lock.json" "-additionalAssemblyPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0\Facade"

**Comment by ritchielozada** [comment]
Similar build issue reported.  Closing this issue for the Video sending limitation.
