### ISSUE TITLE
Nothing In Hololens

### ISSUE THREAD

**Issue by zhangq08** [ritchielozada/UnityWithWebRTC#6]
When I deploy it on Hololens Device and start the application ,but I can not see anything in Hololens Except the TextureQuad.  Anyone can tell me why?

**Comment by ritchielozada** [comment]
The default setup in the Unity/HoloLens app is to display a TextureQuad that receives image frame updates from the WebRTC connection.

The setup guide I posted was for 2 workstations with a dependency on peerconnection_server.exe to manage the peer session.   Since you are using a HoloLens, the peer Visual Studio workstation and HoloLens unit need to be on the same network (wireless or HL wireless + workstation wired through an access point).  You can look at the output of peerconnection_server.exe to see if the HoloLens and Workstation are connected.    A blank TextureQuad would indicate no WebRTC frame updates are being processed.

Please note that a image frame rate on the HoloLens is very low in this sample with Unity and C++.  You can check out [https://github.com/CatalystCode/3dtoolkit](https://github.com/CatalystCode/3dtoolkit) for a native C++ version that has better performance on HoloLens for handling the incoming video frames.

**Comment by ritchielozada** [comment]
reopen issue if needed.

**Comment by eco3** [comment]
I encounter the same problem as @lovelieren.
On HoloLens and in PC the TextureQuad just get's a bit darker when after hitting the "Connect Peer" on XamlTestApp.

I even checked the peerconnection_server.exe and both client are connected to it. Any way to give you a more detailed output? I'm stuck over here, every bit of help would be appreciated. :)

![unitywithwebrtc_notworking](https://user-images.githubusercontent.com/9336616/40000187-79ae51c8-578b-11e8-83b4-6bf9a8eff9a1.PNG)
