### ISSUE TITLE
Is there an interface for the audio play in Unity?

### ISSUE THREAD

**Issue by XxChuckLeexX** [ritchielozada/UnityWithWebRTC#7]
I made it work out in unity, but there is a problem that it has no audio play in Unity.

**Comment by ritchielozada** [comment]
The audio (speaker and microphone) works on the Unity client running on Windows.   However, I intentionally disabled the audio since my main intent was to stream video.   You can enable audio by updating this section:

[WebRtcControl.cs#L178](https://github.com/ritchielozada/UnityWithWebRTC/blob/c3e9d2e28d4fc209f7f9709e8be857e92bf3f170/ExternalProjects/WebRtcIntegration/WebRtcWrapper/WebRtcControl.cs#L178)

**Comment by ritchielozada** [comment]
re-open if needed
